baseurl: "https://objectif-bac.netlify.com/"
title: Objectif bac
favicon_url: ""
description: ""
collections:
  articles:
    output: true
markdown: kramdown
parse_block_html: true
environment: production

math_engine: mathsJax