backend:
  name: git-gateway
  repo: MathisBarre/objectif-bac
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: 'assets/uploads'
site_url: https://objectif-bac.netlify.com
logo_url: https://objectif-bac.netlify.com/assets/img/logo.png

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - name: "articles"
    label: "Articles"
    folder: "_articles"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "article"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Date de publication", name: "date", widget: "datetime"}
      - {label: "Image d'en tête", name: "headerImg", widget: "image", required: false }
      - {label: "Auteur", name: "auteur", widget: "string"}
      - {label: "Lien permanent", name: "permalink", widget: "string", hint: "Exemple : monArticle ou articles/monarticle" }
      - {label: "Body", name: "body", widget: "markdown"}